general {
    # avoid starting multiple hyprlock instances.
    lock_cmd = pidof hyprlock || hyprlock       
    # lock before suspend.
    before_sleep_cmd = playerctl --all-players pause && loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r 
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    # 10min 30s
    timeout = 630        
    # screen off when timeout has passed, save current brightness
    on-timeout = hyprctl dispatch dpms off && brightnessctl -s set 0
    # screen on when activity is detected after timeout has fired
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl hibernate
}
